// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_bWsVK6Djkq-TGC9Wbyds1fDI5fdWUWg',
    appId: '1:696162402950:web:d0f288675a15f5c488c707',
    messagingSenderId: '696162402950',
    projectId: 'feelings-a5451',
    authDomain: 'feelings-a5451.firebaseapp.com',
    storageBucket: 'feelings-a5451.appspot.com',
    measurementId: 'G-ZYXSQ8FV0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnVv43KHXUTfyGD_W_RV2Pf9HkbuALX4I',
    appId: '1:696162402950:android:650830f806c8866a88c707',
    messagingSenderId: '696162402950',
    projectId: 'feelings-a5451',
    storageBucket: 'feelings-a5451.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu8tUFD2x50U8AqHLFoOmWFLOr5NuM6EQ',
    appId: '1:696162402950:ios:8676ba3790cbaea588c707',
    messagingSenderId: '696162402950',
    projectId: 'feelings-a5451',
    storageBucket: 'feelings-a5451.appspot.com',
    iosClientId:
        '696162402950-39rlblpbe6i4umkc5m96jk7587tdid3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.feelings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu8tUFD2x50U8AqHLFoOmWFLOr5NuM6EQ',
    appId: '1:696162402950:ios:8676ba3790cbaea588c707',
    messagingSenderId: '696162402950',
    projectId: 'feelings-a5451',
    storageBucket: 'feelings-a5451.appspot.com',
    iosClientId:
        '696162402950-39rlblpbe6i4umkc5m96jk7587tdid3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.feelings',
  );
}
